name = "fig"
version = "0.1.0"
license = "license"
author = "anonmiraj"
maintainer = "nabilmalek48@gmail.com"
copyright = "Copyright 2024, anonmiraj"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
plutovg-fortran = {git = "https://github.com/AnonMiraj/plutovg-fortran.git" }
