name: Build and Test

on: [push, pull_request]


jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      GCC_V: 12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}



    - name: Install Dependencies Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt install -y gfortran-${GCC_V}
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} 100

    - name: Build and Test Linux 
      if: contains(matrix.os, 'ubuntu') 
      run: |
        which gfortran
        gfortran --version
        fpm test
